version: "3.8"
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,dynamodb,secretsmanager
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
    volumes:
      - "./localstack-bootstrap.sh:/etc/localstack/init/ready.d/bootstrap.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"
