version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running Pre-build tasks..."
      - aws --version
      - ls
  build:
    commands:
      - echo "Running ESBuild bundling..."
      # Run build
      - npm run bundle-esbuild
      # Run tests
      - echo "Running tests..."
      # - npm run test
      
      # Run Coverage
      - echo "Running coverage..."
      - npm run coverage

      # Build and test is done then copy the bundled files to S3
      # Copy the bundled files to arn:aws:s3:::lambda-project-bundle-source-checked
      - ls -la src/rebuild/
      - echo "Copying bundled files to S3..."
      - aws s3 cp src/rebuild/ s3://lambda-project-bundle-source-checked/ --recursive
  post_build:
    commands:
      - echo "Build completed successfully."
      - echo "Listing contents of the S3 bucket:"
      - aws s3 ls s3://lambda-project-bundle-source-checked/
      - echo "Listing contents of the local rebuild directory:"
      - ls -la src/rebuild/
