version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running Pre-build tasks..."
      - aws --version
      - ls -la
  build:
    commands:
      - echo "Running ESBuild bundling..."
      # Run build
      - npm run bundle-esbuild
      # Run tests: TODO
      - ls -la src/rebuild/
      # Build and test is done then copy the bundled files to S3
      # Copy the bundled files to arn:aws:s3:::lambda-project-bundle-source
      - echo "Copying bundled files to S3..."
      - aws s3 cp src/rebuild/ s3://lambda-project-bundle-source/ --recursive
