version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running Pre-build tasks..."
      - ls -la
  build:
    commands:
      - echo "Running ESBuild bundling..."
      - npm run bundle-esbuild
      - ls -la src/rebuild
artifacts:
  files:
    - src/rebuild/**/*  # xuất bundle vào artifacts nếu muốn dùng ở bước khác
